### PR TITLE
Add caching to address api

### PR DESCRIPTION
**Pull request by JonnyDaenen**
## Changes
- Add caching
- Restructure code
- Add basic perf test code

## Review request
- First review other open PR please (this one branches off from that one)
- Code review
- Run unit tests

### CODE REVIEW

**Review by eliavw — CHANGES_REQUESTED** [review]
Looks good to me.

Only very minor comment is that I'd move the performance tests to the tests folder.

Perhaps I'd add a "master test" script (`test_statsector.py`) that runs all tests as well. Since we are not really using CI/CD testing framework here, this could make it easier to quickly run all tests before committing a change.

**Comment by JonnyDaenen** [comment]
@eliavw Moved the testing files and added section to Readme. Can you check if ok?

I did not include a "master test script" for the following reasons:
- we follow standard python unit test conventions and can be run using `python -m unittest discover -s tests`
- perf tests should remain isolated from unit tests as they typically take up more time and have a different goal

Is this ok for you?

**Comment by eliavw** [comment]
Yes, all ok for me.

**Review by eliavw — APPROVED** [review]

**Review by HanneSips — APPROVED** [review]
👌

**Pull request merged**
